/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package schemas.surface_data;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class defective_tile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1136530079483122838L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"defective_tile\",\"namespace\":\"schemas.surface_data\",\"fields\":[{\"name\":\"hash\",\"type\":\"string\"},{\"name\":\"sector\",\"type\":\"string\"},{\"name\":\"tensor\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"double\"}}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence hash;
  @Deprecated public java.lang.CharSequence sector;
  @Deprecated public java.util.List<java.util.List<java.util.List<java.lang.Double>>> tensor;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public defective_tile() {}

  /**
   * All-args constructor.
   */
  public defective_tile(java.lang.CharSequence hash, java.lang.CharSequence sector, java.util.List<java.util.List<java.util.List<java.lang.Double>>> tensor) {
    this.hash = hash;
    this.sector = sector;
    this.tensor = tensor;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return hash;
    case 1: return sector;
    case 2: return tensor;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: hash = (java.lang.CharSequence)value$; break;
    case 1: sector = (java.lang.CharSequence)value$; break;
    case 2: tensor = (java.util.List<java.util.List<java.util.List<java.lang.Double>>>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'hash' field.
   */
  public java.lang.CharSequence getHash() {
    return hash;
  }

  /**
   * Sets the value of the 'hash' field.
   * @param value the value to set.
   */
  public void setHash(java.lang.CharSequence value) {
    this.hash = value;
  }

  /**
   * Gets the value of the 'sector' field.
   */
  public java.lang.CharSequence getSector() {
    return sector;
  }

  /**
   * Sets the value of the 'sector' field.
   * @param value the value to set.
   */
  public void setSector(java.lang.CharSequence value) {
    this.sector = value;
  }

  /**
   * Gets the value of the 'tensor' field.
   */
  public java.util.List<java.util.List<java.util.List<java.lang.Double>>> getTensor() {
    return tensor;
  }

  /**
   * Sets the value of the 'tensor' field.
   * @param value the value to set.
   */
  public void setTensor(java.util.List<java.util.List<java.util.List<java.lang.Double>>> value) {
    this.tensor = value;
  }

  /**
   * Creates a new defective_tile RecordBuilder.
   * @return A new defective_tile RecordBuilder
   */
  public static schemas.surface_data.defective_tile.Builder newBuilder() {
    return new schemas.surface_data.defective_tile.Builder();
  }
  
  /**
   * Creates a new defective_tile RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new defective_tile RecordBuilder
   */
  public static schemas.surface_data.defective_tile.Builder newBuilder(schemas.surface_data.defective_tile.Builder other) {
    return new schemas.surface_data.defective_tile.Builder(other);
  }
  
  /**
   * Creates a new defective_tile RecordBuilder by copying an existing defective_tile instance.
   * @param other The existing instance to copy.
   * @return A new defective_tile RecordBuilder
   */
  public static schemas.surface_data.defective_tile.Builder newBuilder(schemas.surface_data.defective_tile other) {
    return new schemas.surface_data.defective_tile.Builder(other);
  }
  
  /**
   * RecordBuilder for defective_tile instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<defective_tile>
    implements org.apache.avro.data.RecordBuilder<defective_tile> {

    private java.lang.CharSequence hash;
    private java.lang.CharSequence sector;
    private java.util.List<java.util.List<java.util.List<java.lang.Double>>> tensor;

    /** Creates a new Builder */
    private Builder() {
      super(schemas.surface_data.defective_tile.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schemas.surface_data.defective_tile.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.hash)) {
        this.hash = data().deepCopy(fields()[0].schema(), other.hash);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sector)) {
        this.sector = data().deepCopy(fields()[1].schema(), other.sector);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tensor)) {
        this.tensor = data().deepCopy(fields()[2].schema(), other.tensor);
        fieldSetFlags()[2] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing defective_tile instance
     * @param other The existing instance to copy.
     */
    private Builder(schemas.surface_data.defective_tile other) {
            super(schemas.surface_data.defective_tile.SCHEMA$);
      if (isValidValue(fields()[0], other.hash)) {
        this.hash = data().deepCopy(fields()[0].schema(), other.hash);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sector)) {
        this.sector = data().deepCopy(fields()[1].schema(), other.sector);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tensor)) {
        this.tensor = data().deepCopy(fields()[2].schema(), other.tensor);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'hash' field.
      * @return The value.
      */
    public java.lang.CharSequence getHash() {
      return hash;
    }

    /**
      * Sets the value of the 'hash' field.
      * @param value The value of 'hash'.
      * @return This builder.
      */
    public schemas.surface_data.defective_tile.Builder setHash(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.hash = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'hash' field has been set.
      * @return True if the 'hash' field has been set, false otherwise.
      */
    public boolean hasHash() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'hash' field.
      * @return This builder.
      */
    public schemas.surface_data.defective_tile.Builder clearHash() {
      hash = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sector' field.
      * @return The value.
      */
    public java.lang.CharSequence getSector() {
      return sector;
    }

    /**
      * Sets the value of the 'sector' field.
      * @param value The value of 'sector'.
      * @return This builder.
      */
    public schemas.surface_data.defective_tile.Builder setSector(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sector = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'sector' field has been set.
      * @return True if the 'sector' field has been set, false otherwise.
      */
    public boolean hasSector() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sector' field.
      * @return This builder.
      */
    public schemas.surface_data.defective_tile.Builder clearSector() {
      sector = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tensor' field.
      * @return The value.
      */
    public java.util.List<java.util.List<java.util.List<java.lang.Double>>> getTensor() {
      return tensor;
    }

    /**
      * Sets the value of the 'tensor' field.
      * @param value The value of 'tensor'.
      * @return This builder.
      */
    public schemas.surface_data.defective_tile.Builder setTensor(java.util.List<java.util.List<java.util.List<java.lang.Double>>> value) {
      validate(fields()[2], value);
      this.tensor = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'tensor' field has been set.
      * @return True if the 'tensor' field has been set, false otherwise.
      */
    public boolean hasTensor() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tensor' field.
      * @return This builder.
      */
    public schemas.surface_data.defective_tile.Builder clearTensor() {
      tensor = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public defective_tile build() {
      try {
        defective_tile record = new defective_tile();
        record.hash = fieldSetFlags()[0] ? this.hash : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sector = fieldSetFlags()[1] ? this.sector : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tensor = fieldSetFlags()[2] ? this.tensor : (java.util.List<java.util.List<java.util.List<java.lang.Double>>>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
