services:
    spark-master:
        image: bitnami/spark:latest
        ports:
            - "8080:8080"  # Spark master UI
            - "7077:7077"  # Spark master port
        environment:
            - SPARK_MODE=master

    spark-worker:
        image: bitnami/spark:latest
        ports:
            - "8081:8081"  # Spark worker UI
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
        depends_on:
            - spark-master
