REM CONTAINER PARAMS
SET DOCKERFILE=dind.Dockerfile
SET DOCKER_IMAGE=cluster_node_img
SET CONTAINER_NAME=cluster_node

REM OBTAIN 2CHAR NUMERIC MACHINE SUFFIX
REM CLASSROOM MACHINES FOLLOW PATTERN "F365-0XX"
set FULL_NAME=%COMPUTERNAME%
set NTH_MACHINE=%FULL_NAME:~6,2%

REM BUILD THE CONTAINER
docker build -t %DOCKER_IMAGE% -f %DOCKERFILE% .

REM START THE CONTAINER
docker run -e NTH_CLUSTER_NODE=%NTH_MACHINE% -d --rm --privileged --name %CONTAINER_NAME% %DOCKER_IMAGE%

REM START THE REVERSE TUNNEL -- INSIDE OF CONTAINER
docker exec %CONTAINER_NAME% /bin/bash /cluster/create_ssh_tunnel.sh