services:

    # GOOD HARDWARE INFORMATION
    node-exporter:
        image: prom/node-exporter:v1.6.0
        ports:
            - 9100:9100

    # NVIDIA GPU METRICS
    dcgm-exporter:
        image: nvidia/dcgm-exporter:latest
        environment:
            - DCGM_EXPORTER_PORT=9400

            # PUBLISH NEW METRICS EVERY 1s -- DEFAULT IS 30s
            - DCGM_EXPORTER_INTERVAL=1000
        ports:
            - "9400:9400"

        # ENABLES GPU RUNTIME
        # REMEMBER TO INSTALL nvidia-container-toolkit
        # REMEMBER TO UPDATE /etc/docker/daemon.json WITH NVIDIA
        runtime: nvidia
        cap_add:
            - SYS_ADMIN