services:

    # GOOD HARDWARE INFORMATION
    node-exporter:
        image: prom/node-exporter:v1.6.0
        ports:
            - 9100:9100

    dcgm-exporter:
        image: nvidia/dcgm-exporter:latest
        container_name: dcgm-exporter
        restart: unless-stopped
        environment:
            - DCGM_EXPORTER_PORT=9400   # Port for the exporter
        ports:
            - "9400:9400"               # Exposing the port for Prometheus scraping
        runtime: nvidia               # Enable GPU access for the container
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - capabilities: [gpu]  # Ensure the container has access to GPUs