cluster:

    # MESSAGE QUEUE
    kafka_brokers:
        - 193.166.180.240:11001

    # DATABASE
    cassandra_brokers:
        - 193.166.180.240:12001

    # REDIS CACHE
    redis_broker: 193.166.180.240:6379

    # MLFLOW
    mlflow_broker: 193.166.180.240:5000

###############################################################################################################
###############################################################################################################

# BACKEND API SETTINGS
backend:

    # WHAT PORT SHOULD THE BACKEND API BE RUNNING ON?
    api_port: 3003

    # HIDE/SHOW LOG STATEMENTS
    verbose_logging: true

    # HIDE AUXILLARY TABLES AND TOPICS FROM BACKEND LISTINGS?
    # MAKES IT EASIER TO READ/FIND RELEVANT DATA
    hide_auxillary: true

    # WHAT CONTENT SHOULD BE AUTO-CREATED BY THE INIT ENDPOINTS?
    create_on_init:

        # KAFKA TOPICS
        # JUST THE TOPIC NAME IS ENOUGH
        kafka_topics:
            - data_refinery
            - model_dispatch
            - decision_synthesis

        # CASSANDRA KEYSPACES/TABLES
        # PROVIDE A KEYSPACE, TABLE NAME, ITS COLUMNS AND WHAT COLS SHOULD BE USED AS COMPOSITE KEYS
        cassandra_tables:

            # REFINED STOCK DATA TABLE
            -   keyspace: dev
                table_name: refined_stock_data
                columns: 
                    symbol: text
                    timestamp: int
                    high: float
                    low: float
                    open: float
                    close: float
                    adjusted_close: float
                    volume: int
                primary_keys:
                    - symbol
                    - timestamp

        # REDIS KEYSPACES
        redis:
            model_pipelines: {}

###############################################################################################################
###############################################################################################################

# PYTHON PIPELINE SETTINGS
pipeline:

    # HIDE/SHOW LOG STATEMENTS
    verbose_logging: true

    # FOR HOW LONG SHOULD POLLING CLIENTS TIMEOUT?
    # PREVENTS BUSY-WAITING
    polling_cooldown: 0.3

    # KAFKA CONSUMER SETTINGS
    kafka:

        # WHEN A CONSUMER IS BOOTED UP..
        # WHAT INDEX SHOULD IT START READING FROM?
        consumer_stategy: latest

        # SHOULD CONSUMERS AUTO COMMIT OR NOT?
        consumer_auto_commit: false
        async_consumer_commit: true

        # HOW SHOULD PRODUCERS ACKNOWLEDGE?
        async_producer_ack: true

    ###############################################################################################################
    ###############################################################################################################