# CLUSTER SYSTEM BROKERS
cluster:

    # KAFKA MESSAGE QUEUE
    kafka_brokers:
        - localhost:11001
        - localhost:11002

    # CASSANDRA DB
    cassandra_brokers:
        - localhost:12001
        - localhost:12002

    # REDIS CACHE
    redis_broker: localhost:6379

###############################################################################################################
###############################################################################################################

# BACKEND API SETTINGS
backend:

    # WHAT PORT SHOULD THE BACKEND API BE RUNNING ON?
    api_port: 3003

    # HIDE AUXILLARY TABLES AND TOPICS FROM BACKEND LISTINGS?
    # MAKES IT EASIER TO READ/FIND RELEVANT DATA
    hide_auxillary: true

    # WHAT CONTENT SHOULD BE AUTO-CREATED BY THE INIT ENDPOINTS?
    create_on_init:

        # KAFKA TOPICS
        # JUST THE TOPIC NAME IS ENOUGH
        kafka_topics:
            - data_refinery
            - data_dispatch
            - model_training
            - model_inference
            - model_analysis
            - decision_synthesis

        # CASSANDRA KEYSPACES/TABLES
        # PROVIDE A KEYSPACE, TABLE NAME, ITS COLUMNS AND WHAT COLS SHOULD BE USED AS COMPOSITE KEYS
        cassandra_tables:
            -   keyspace: refined
                table_name: stock_data
                columns: 
                    timestamp: int
                    open: float
                    close: float
                    high: float
                    low: float
                    volume: int
                primary_keys:
                    - timestamp

###############################################################################################################
###############################################################################################################

# PYTHON PIPELINE SETTINGS
pipeline:

    # HIDE/SHOW LOG STATEMENTS
    verbose_logging: true

    # KAFKA CONSUMER SETTINGS
    kafka:

        # WHEN A CONSUMER IS BOOTED UP..
        # WHAT INDEX SHOULD IT START READING FROM?
        consumer_stategy: latest

        # SHOULD CONSUMERS AUTO COMMIT OR NOT?
        consumer_auto_commit: false
        async_consumer_commit: true

        # HOW SHOULD PRODUCERS ACKNOWLEDGE?
        async_producer_ack: true

    # MACHINE LEARNING STUFF
    machine_learning:

        # DO YOU WANT TO USE PRE-CREATED MODELS FROM FILES?
        # LIST OF FILES, OR FALSE
        load_premade_models: false

        # WHAT NEW MODELS SHOULD BE CREATED
        create_models:
            -   type: cnn
                name: my_first_model
                version: 1
            -   type: linreg
                name: my_second_model
                version: 1
            -   type: lstm
                name: my_third_model
                version: 1



    MODEL_NAME::MODEL_TYPE::VERSION_NUM

    my_third_model::lstm::v1