services:
    spark-worker:
        image: bitnami/spark:latest
        user: "0"
        ports:
            - "8081:8081"  # Spark worker UI
        volumes:
            - ./spark-env.sh:/opt/bitnami/spark/conf/spark-env.sh
            #- ./rapids-4-spark_2.12-24.08.0.jar:/opt/bitnami/spark/jars/rapids-4-spark_2.12-24.08.0.jar
            - ./getGpusResources.sh:/opt/bitnami/spark/conf/getGpusResources.sh
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://193.167.37.47:7077
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: 2
                            capabilities: [gpu]
