services:
    spark-worker:
        image: bitnami/spark:latest
        user: root
        ports:
            - "8081:8081"
        volumes:
            - ./spark-env.sh:/opt/bitnami/spark/conf/spark-env.sh
            - ./getGpusResources.sh:/opt/bitnami/spark/conf/getGpusResources.sh
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://193.167.37.47:7077
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: 2
                            capabilities: [gpu]