# SHARED KAFKA VARS
x-kafka_shared: &kafka_shared
    image: confluentinc/cp-kafka:7.3.0
    volumes:
        - ./configs/kafka_scraper.yml:/usr/app/kafka_scraper.yml
        - ./jars/jmx_prometheus_javaagent-0.17.2.jar:/usr/app/jmx_prometheus_javaagent.jar
    depends_on:
        - kafka_zookeeper

# SHARED KAFKA ENV
x-kafka_env: &kafka_env
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: False
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_ZOOKEEPER_CONNECT: kafka_zookeeper:2181
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    KAFKA_JMX_OPTS: "-javaagent:/usr/app/jmx_prometheus_javaagent.jar=13000:/usr/app/kafka_scraper.yml"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

services:

    # ZOOKEEPER FOR BROKER MANAGEMENT
    kafka_zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2

    # ONLY THE FORWARDED PORTS AND AD. STRING ARE DIFFERENT FOR EACH BROKER
    kafka_broker_1:
        <<: *kafka_shared
        ports:
            - '11001:11001'
        environment:
            <<: *kafka_env
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_1:11000,PLAINTEXT_HOST://localhost:11001

    kafka_broker_2:
        <<: *kafka_shared
        ports:
            - '11002:11002'
        environment:
            <<: *kafka_env
            KAFKA_BROKER_ID: 2
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_2:11000,PLAINTEXT_HOST://localhost:11002