services:

    # SCRAPES METRIC DATA FROM EACH SYSTEM
    prometheus:
        image: prom/prometheus:v2.43.0
        volumes:
            - ./configs/prometheus_config.yml:/etc/prometheus/config.yml
        ports:
            - '9090:9090'
        command:
            - '--config.file=/etc/prometheus/config.yml'

    # VISUALIZES THE DATA FROM PROMETHEUS
    grafana:
        image: grafana/grafana-oss:9.4.1
        volumes:
            - ./grafana/datasources:/etc/grafana/provisioning/datasources/
            - ./grafana/dashboard_config.yml:/etc/grafana/provisioning/dashboards/main.yaml
            - ./grafana/dashboards/:/var/lib/grafana/dashboards
            - ./grafana/server.ini:/etc/grafana/grafana.ini
        ports:
            - '9091:3000'
    
    # PROMETHEUS METRICS: GOOD HARDWARE INFO
    node-exporter:
        image: prom/node-exporter:v1.6.0

    # PROMETHEUS METRICS: DOCKER CONTAINER INFO
    cadvisor:
        image: gcr.io/cadvisor/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk:/dev/disk/:ro