global:
    scrape_interval: 1s # By default, scrape targets every 15 seconds.
scrape_configs:

    # KAFKA BROKER SCRAPERS
    -   job_name: kafka
        metrics_path: /metrics
        static_configs:
            - targets:
                - kafka_broker_1:13000
                - kafka_broker_2:13000

    # CASSANDRA BROKER SCRAPERS
    -   job_name: cassandra
        metrics_path: '/metrics'
        static_configs:
            - targets:
                - cassandra_1:13000
                - cassandra_2:13000

    # FLINK CLUSTER SCRAPING
    -   job_name: flink
        metrics_path: /metrics
        static_configs:
            - targets:
                - jobmanager:13000
                - taskmanager_1:13000

    # SCRAPE DOCKER CONTAINERS
    -   job_name: cadvisor
        metrics_path: /metrics
        static_configs:
            - targets:
                - cadvisor:8080

    -   job_name: node
        static_configs:
            - targets:
                - node-exporter:9100