# MISC EXPERIMENT DETAILS
experiment:
    name: my_first_experiment
    version: 1

# FETCH DATASET FROM CASSANDRA
dataset:
    db_table: shohel.refined_stock_data
    stock_symbol: AAPL

    # FORMAT: %Y-%m-%d %H:%M:%S
    timestamps:
        start: '2019-01-01 00:00:00'
        end: '2019-01-10 00:00:00'

    # PROVIDE A MIN ROW COUNT FOR THE DATASET
    # FOR SANITY CHECKING
    min_length_threshold: 10

    # EXPECTED ROW SCHEMA
    expected_schema:
        symbol: str
        timestamp: str
        open: float
        close: float
        high: float
        low: float
        volume: int

# APPLY FEATURES
segmentation:
    - train: 0.75
    - test: 0.1
    - validate: 0.15

# TRADING STRATEGY
trading_strategy:
    strategy_name: foobar
    batch_size: 3
    init:
        capital: 100
        stocks: 0


# # APPLY FEATURES
# feature_engineering:
#     foo: bar