# MISC EXPERIMENT DETAILS
experiment:
    name: my_first_experiment
    version: 1

# FETCH DATASET FROM CASSANDRA
dataset:
    db_table: shohel.refined_stock_data
    stock_symbol: AAPL

    # FORMAT: %Y-%m-%d %H:%M:%S
    timestamps:
        start: '2019-01-01 00:00:00'
        end: '2019-01-10 00:00:00'

    # PROVIDE A MIN ROW COUNT FOR THE DATASET
    # FOR SANITY CHECKING
    min_length_threshold: 10

# APPLY FEATURES
feature_engineering:
    foo: bar

# APPLY FEATURES
segmentation:
    - train: 0.75
    - validate: 0.15
    - test: 0.1