services:
    spark-master:
        image: bitnami/spark:latest
        ports:
            - "8080:8080"  # Spark master UI
            - "7077:7077"  # Spark master port
        environment:
            - SPARK_MODE=master

    spark-worker:
        image: spark-gpu
        ports:
            - "8081:8081"  # Spark worker UI
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            # - SPARK_LOCAL_IP=spark-worker
        runtime: nvidia  # Enable GPU support
        command: ["spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 -   driver: nvidia
        #                     count: all  # Or specify the number of GPUs you want to allocate


### docker build -t spark-gpu .
### docker build -t spark-gpu .
### docker build -t spark-gpu .
### docker build -t spark-gpu .