{
 "title": "ARCADA_CLUSTER",
 "description": "This dashboard is to display the metrics from DCGM Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TOTAL MACHINES ONLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "TOTAL CPU CORES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"node\", mode=\"idle\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "TOTAL GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(DCGM_FI_DEV_FB_USED{})", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL{}", "legendFormat": "{{instance}} GPU #{{gpu}}" }
   ]
  },
  {
   "title": "GPU MEMORY USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED{}", "legendFormat": "{{instance}} GPU #{{gpu}}" }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum by(instance) (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node\"}[$__rate_interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"} - (node_memory_Cached_bytes{job=\"node\"} + node_memory_Buffers_bytes{job=\"node\"} + node_memory_SReclaimable_bytes{job=\"node\"})) / node_memory_MemTotal_bytes{job=\"node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}